name: Build and release

on:
  push:
    branches: [main]

jobs:
  build_emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.50

      - name: Build
        run: emmake make CC=emcc -Werror

      - name: Create zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          filename: lakesnes_web.zip
          path: index.html index.js index.wasm LICENSE.txt

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: LakeSnes_Web
          path: lakesnes_web.zip

            LakeSnes nightly release (build ${{ github.run_number }}).

            WebAssembly build compiled using Emscripten.
          files: ./LakeSnes_*/*.zip
